Initial import from the private TL repo.
trafficland/augment-sbt pull request #1
Opened 2017-01-12 03:09 UTC by ereichert

2017-01-19 16:07 UTC, ryandbair requested changes

2017-01-19 16:07 UTC, ryandbair commented on build.sbt
> +    remoteGitRepoPatterns                 ++= Seq("""^git@github.com:ereichert/.*\.git""".r, """^https://github.com/ereichert/.*\.git""".r),
Should be trafficland, no?

2017-01-19 16:07 UTC, ryandbair commented on src/main/java/com/trafficland/augmentsbt/ConsoleCredentialsProvider.java
> +public class ConsoleCredentialsProvider extends CredentialsProvider {
Oh, interesting. Does this actually work with SBT? 

It looks like this is included in the org.eclipse.jgit.pgm jar. It took a little digging, but I finally found reference to their existence: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.eclipse.jgit%22%20AND%20a%3A%22org.eclipse.jgit.pgm%22

That should be included in plugins.sbt.

2017-01-19 16:07 UTC, ryandbair commented on src/main/resources/init.sh.template
> +#!/bin/sh
We can get rid of this. Native packager brings in it's own template.

2017-01-19 16:07 UTC, ryandbair commented on src/main/resources/nginx.conf.template
> +server {
This file is also unused.

2017-01-19 16:20 UTC, ereichert commented
@ryandbair In general, this isn't ready for review. I should have deleted the PR.

2017-01-19 16:20 UTC, ereichert commented on build.sbt
> +    remoteGitRepoPatterns                 ++= Seq("""^git@github.com:ereichert/.*\.git""".r, """^https://github.com/ereichert/.*\.git""".r),
Once I finish testing, yes.

2017-01-19 16:22 UTC, ereichert commented on src/main/java/com/trafficland/augmentsbt/ConsoleCredentialsProvider.java
> +public class ConsoleCredentialsProvider extends CredentialsProvider {
Yes. It works as it is. The plugin however does not. That class never made it to release as far as I can tell. We only need those two bits of code so copying the code seems reasonable.

2017-01-19 16:22 UTC, ereichert commented on src/main/resources/init.sh.template
> +#!/bin/sh
10-4

2017-01-19 16:22 UTC, ereichert commented on src/main/resources/nginx.conf.template
> +server {
10-4

2017-01-21 04:57 UTC, ereichert commented
@ryandbair This is finally ready to be reviewed.

2017-02-01 21:50 UTC, ereichert commented
@ryandbair or @cchampignon Could one of you finish this up?

2017-02-01 21:51 UTC, ryandbair commented
Will do.

2017-02-04 17:28 UTC, ryandbair requested changes

2017-02-04 17:28 UTC, ryandbair commented on project/KeyGenerator.scala
> +      IO.write(targetFile, "bin/generate-keys".!!)
generate-keys and generate-keys.rb aren't checked in. 

Long term, I think it makes sense to reorganize the keys into different traits with companion objects and combine the traits into larger objects, similar to what other sbt plugins are doing.

2017-02-04 17:28 UTC, ryandbair commented on .github/PULL_REQUEST_TEMPLATE.md
> +**Before you do anything else,
I never knew this was a thing. Nifty.

2017-02-04 17:28 UTC, ryandbair commented on src/main/java/com/trafficland/augmentsbt/ConsoleCredentialsProvider.java
> +public class ConsoleCredentialsProvider extends CredentialsProvider {
I have a commit which fixes this. PR inbound.

2017-02-05 16:02 UTC, ereichert commented on project/KeyGenerator.scala
> +      IO.write(targetFile, "bin/generate-keys".!!)
Resolved.

2017-02-05 16:03 UTC, ereichert commented
@ryandbair This includes your PR. It's ready to be merged.

2017-02-06 14:18 UTC, ryandbair approved these changes

2017-02-06 14:18 UTC, merged